###########################################################################################
###                                     IMPORTANT:                                      ###
###                  Document created by Fernando Barranco Rodríguez                    ###
###                    Data Science Specialization (R Programming)                      ###
###                        Coursera - Johns Hopkins University                          ###
###########################################################################################

# 'makeCacheMatrix' creates a special "matrix" object that can cache its inverse.
# 'cacheSolve' computes the inverse of the special "matrix" returned by 'makeCacheMatrix'. 

# This function creates a list of four set-and-retrieve functions.

makeCacheMatrix <- function(x = matrix()) {

        m <- NULL  # Empty "vector"
        set <- function(y) {  # Set matrix
                x <<- y
                m <<- NULL
        }
        get <- function() x  # Return matrix
        setinv <- function(inv) m <<- inv  # Set inverse 
        getinv <- function() m  # Return inverse of matrix
        list(set = set, get = get, 
             setinv = setinv,
             getinv = getinv)  # Return list of methods 
        
}

# This function takes as its argument the list generated by the previous function,
# checks if the inverse has already been calculated, if it is the case then the inverse
# is retrieved from cache, if not then proceeds to calculate it.

cacheSolve <- function(x, ...) {
        
        m <- x$getinv()  # Return "x" inverse matrix
        if(!is.null(m)) {  # Return inverse if already set
                message("getting cached data")
                return(m)
        }
        data <- x$get()  # Get matrix 
        m <- solve(data, ...)  # Calculate inverse
        x$setinv(m)  # Set inverse
        m  # Return matrix
        
}